runtime: nodejs18
instance_class: F1

env: standard

env_variables:
  MONGODB_URI: "your_production_mongo_connection_string"
  JWT_SECRET: "your_secret_key"
  REACT_APP_BYPASS_AUTH: "false"
  REACT_APP_USER_ROLE: "regular"

handlers:
  - url: /.*
    script: auto